### PR TITLE
Dockerfile proposition for kansha

### PR DESCRIPTION
**Pull request by ygravrand**
Available on dockerhub:
docker run -p 8080:8080 ygravrand/kansha

### CODE REVIEW

**Comment by ygravrand** [comment]
@ephilippot for now you can use `user1`, `user2`, `user3` as users and `password` as password.
I will document this and look up the other deps problem tonight.
Are you sure you want to include a smtp server running on localhost?...
A better approach would be to have Nagare pick up env variables in conf to hook up to an existing smtp server, or link to another container doing just that.

**Comment by ephilippot** [comment]
Your solution is better. For the moment env variables in conf to hook up to an existing smtp server is fine.

**Comment by rtxm** [comment]
Don't forget to `python setup.py compile_catalog` to have translations enabled before installing from sources.

**Comment by rtxm** [comment]
Pulled and rebased into docker branch.

**Pull request closed without merging**
